### ISSUE TITLE
example with controlnet

### ISSUE THREAD

**Issue by haile-vnu** [junjiehe96/UniPortrait#10]
Hi @junjiehe96 ,

Thank you very much for your amazing work.
I saw 3 demos in your Gradio app. Could you guide me on how to use Controlnet for the demo?

Many Thanks!

**Comment by junjiehe96** [comment]
We use the standard diffusers StableDiffusionControlNetPipeline. Example code is [here](https://huggingface.co/lllyasviel/control_v11p_sd15_openpose).

**Comment by haile-vnu** [comment]
Thank you very much for your instruction.
