### ISSUE TITLE
Model release

### ISSUE THREAD

**Issue by christophschuhmann** [junjiehe96/UniPortrait#2]
When will you release the model ? :)

**Comment by k18coldwl** [comment]
Alibaba Group, I think you know what that means.

**Comment by junjiehe96** [comment]
Thank you for your interest in our work. This project is solely for academic research. We are currently finalizing the model and conducting the last checks. All code and models will be released in approximately 2 months. Please stay tuned! :)

**Comment by junjiehe96** [comment]
Model has been released. So, we close this issue.
