### ISSUE TITLE
About the router

### ISSUE THREAD

**Issue by cpis7** [junjiehe96/UniPortrait#7]
Thanks for your great contribution!
Could you explain more about the router implementations?
I tried to find the details on router but it couldn't find that on the paper,
What kind of network you used for the router network?

**Comment by junjiehe96** [comment]
The definition of router can be found in [Eq.2,](https://arxiv.org/pdf/2408.05939) and you can implement it in any way you like, adjusting its parameter size according to your task. In our original implementation, we used the Eq.3 to implement the router, where $`\theta`$ and $`\phi`$ are instantiated as two 2-layer MLPs (Sec.3.3).

**Comment by 963658029** [comment]
Can you provide some code reference? Thanks

**Comment by junjiehe96** [comment]
> Can you provide some code reference? Thanks

hi, the code will be available next month.
